server:
  port: 20298

logging:
  base: /data0/www/applogs
  path: ${logging.base}/${spring.application.domain}

spring:
  application:
    domain: dev-house.intelligent.tools.mls.lianjia.com
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://10.30.128.219:3306/house_intelligent_tools?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 10
      query-timeout: 10
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      use-global-data-source-stat: true
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      slf4j:
        enabled: true
        data-source-log-enabled: true
        connection-log-enabled: false
        connection-log-error-enabled: true
        statement-log-enabled: true
        statement-log-error-enabled: true
        statement-sql-format-option:
          upp-case: true
          pretty-format: false
        statement-sql-pretty-format: false
        statement-parameter-set-log-enabled: false
        statement-prepare-after-log-enabled: false
        statement-close-after-log-enabled: false
        statement-executable-sql-log-enable: true
        result-set-log-enabled: false
        result-set-log-error-enabled: true
      wall:
        enabled: true
        db-type: mysql
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
          multi-statement-allow: true
      stat-view-servlet:
        enabled: true

  dubbo:
    application:
      name: ${spring.application.name}
    registries:
      mls:
        address: dev-zookeeper.ares.lianjia.com:2181
        group: /qianqian/dubbo
        username: qianqian
        password: 7c75GY5801K
        file: /data0/www/cache/dubbo/${spring.application.name}/mls_zk
      jichu:
        address: zk01-test.lianjia.com:2181,zk02-test.lianjia.com:2181,zk03-test.lianjia.com:2181
        group: /redstardev
        username: redstardev
        password: BC99901adE
        file: /data0/www/cache/dubbo/${spring.application.name}/jichu_zk
      qianqian:
        address: dev-zookeeper.ares.lianjia.com:2181
        group: /qianqian/dubbo
        username: qianqian
        password: 7c75GY5801K
        file: /data0/www/cache/dubbo/${spring.application.name}/qianqian_zk
      alliance_api:
        address: zk01-test.lianjia.com:2181
        group: /home2/qianqian/dubbo
        username: home2
        password: bab5ff85
        file: /data0/www/cache/${spring.application.name}/dubbo/alliance_api_zk
    protocol:
      name: dubbo
      port: 7810
    provider:
      timeout: 5000
      retries: 1
    consumer:
      timeout: 5000
      retries: 0

hawk:
  app-name: ${spring.application.name}
  server:
    host: 10.10.5.77
    socket-port: 8108
  jvm:
    direct-memory: false
  dubbo:
    enabled: true

recommend:
  domain: http://i.bk-house-api.ke.com
